### ISSUE TITLE
 Loader plugin did not call the load callback in the build

### ISSUE THREAD

**Issue by OliverJAsh** [mikach/requirejs-babel#17]
When I run two builds concurrently (i.e. using grunt-concurrent), I get this error:

```
{ [Error: Error: Loader plugin did not call the load callback in the build:
transpile:
  transpile!es6/bootstraps/crosswords_unnormalized2: Error: Load timeout for modules: transpile!es6/bootstraps/crosswords_unnormalized2
http://requirejs.org/docs/errors.html#timeout
Module loading did not complete for:
    at Function.build.checkForErrors (/Users/OliverJAsh/Development/frontend/node_modules/requirejs/bin/r.js:30026:19)
]
  originalError:
   [Error: Loader plugin did not call the load callback in the build:
   transpile:
     transpile!es6/bootstraps/crosswords_unnormalized2: Error: Load timeout for modules: transpile!es6/bootstraps/crosswords_unnormalized2
   http://requirejs.org/docs/errors.html#timeout
   Module loading did not complete for: ] }
```

Do you have any ideas why this might be?

**Comment by szarouski** [comment]
@OliverJAsh I have the same issue with jsx-requirejs-plugin sometimes (also using grunt-concurrent), so it must be an issue with requirejs.

**Comment by OliverJAsh** [comment]
Posted an issue in r.js https://github.com/jrburke/r.js/issues/859

**Comment by kayneb** [comment]
I'm hitting this issue without using grunt-concurrent, and it's intermittent. Sometime my r.js build succeeds. other times it fails relatively quickly with:

```
{ [Error: Error: Loader plugin did not call the load callback in the build:
es6:
  es6!amkt/vendor-reporting/components/vendor-reporting_unnormalized2
  es6!amkt/vendor-reporting/components/vendor-reporting
Module loading did not complete for: amkt/vendor-form/edit-vendor-form, amkt/vendor-reporting/controller
    at Function.build.checkForErrors (/Users/kbarclay/src/amkt/node_modules/requirejs/bin/r.js:30026:19)
]
  originalError:
   [Error: Loader plugin did not call the load callback in the build:
   es6:
     es6!amkt/vendor-reporting/components/vendor-reporting_unnormalized2
     es6!amkt/vendor-reporting/components/vendor-reporting
   Module loading did not complete for: amkt/vendor-form/edit-vendor-form, amkt/vendor-reporting/controller] }
```

**Comment by pietvanzoen** [comment]
I'm also seeing this. Any solutions?

**Comment by wangjingfei** [comment]
Same problem with me. It happens sometimes, not always. I'm using grunt-requirejs.

**Comment by kayneb** [comment]
I found that we were actually parallelizing some of the build in sbt, so that's what resulted in this issue. Make sure to verify you aren't concurrently running parts of your build!

**Comment by martin-liu** [comment]
+1
